name: Deploy Application Prod AWS EC2

on:
  push:
    branches: [main]

jobs:

  deploy:
    needs: build
    runs-on: prod
    steps:
      - name: Pull image from docker hub
        run: sudo docker pull williambreda/sistema-escolar:latest
      - name: Remove docker container
        run: sudo docker rm -f sistema-escolar
      - name: Run docker container
        run: sudo docker run -d -p 8080:8080 -e DATABASE_USERNAME=${{secrets.DATABASE_USERNAME}} -e DATABASE_PASSWORD='${{secrets.DATABASE_PASSWORD}}' -e DATABASE_URL_PROD=${{secrets.DATABASE_URL}} --name sistema-escolar williambreda/sistema-escolar

