name: Deploy Application AWS EC2

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build project
        run: mvn clean install -DskipTests
      - name: Login Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t williambreda/sistema-escolar .
      - name: Push image docker
        run: docker push williambreda/sistema-escolar

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: sudo docker pull williambreda/sistema-escolar:latest
      - name: Remove docker container
        run: sudo docker rm -f sistema-escolar
      - name: Run docker container
        run: sudo docker run -d -p 8080:8080 --name sistema-escolar williambreda/sistema-escolar